### ISSUE TITLE
Residual connection

### ISSUE THREAD

**Issue by ohmiya** [chl8856/DeepHit#1]
Hello,
I'm looking for methods of the survival analysis to find biomarkers for colon cancer treatment.
I am wondering if we could use the python scripts you released, and I have a question about the code.
You mention that residual connections are removed in the code, but the original data seem to be used as the input of the cause-specific sub-networks as well as the output of the shared sub-network.
Do you mean that residual connections are not considered in forward/back propagation modules?
Also, do you happen to have DeepHit codes with residual connections?

Thank you.

**Comment by chl8856** [comment]
@ohmiya 
Thanks for your interest and sorry for the late reply.
In the released code, we removed since we found out, through applying our model to many different datasets, that the performance was not much affected by the residual connections.  Indded, finding good hyper-parameters was more crucial.

Thanks,
Changhee
